---
- hosts: all
  gather_facts: true
  vars_files:
    - vars/gradle_docker_paths.yml

  tasks:
    - name: Change JIB Base Image
      ansible.builtin.lineinfile:
        path: "{{ item }}"
        search_string: 'search-string'
        line: 'replace-string'
      with_items: "{{ gradle_path }}"
...